name: Release
on:
  workflow_dispatch:
  
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - name: Git config
        run: |
          git config user.name autograding-release-bot
          git config user.email autograding-release-bot+education@github.com
      - name: Run build and commit to releases/v3
        run: |
          git reset --hard origin/main
          npm install --silent
          npm run build
          git add dist/
          git commit -m "Release v3"
          git push -f origin releases/v3
      - name: Tag and push v3
        run: |
          git tag -f v3 # Since we are already on releases/v3 we don't need a ref. This will tag HEAD of releases/v3.
          git push origin v3 --force
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: v3
          allowUpdates: true
